# Dockerfile.backend

FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY . .

RUN uv sync

EXPOSE 8000

WORKDIR /app/src

CMD ["uv", "run", "uvicorn", "api.route:app", "--host", "0.0.0.0", "--port", "8000"]